# Generated by Django 3.2 on 2022-09-12 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220911_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
