# Generated by Django 3.2 on 2022-09-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_bid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
